---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: update apt and cahche
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
  
  tasks:
    - name: get software for apt repository
      apt:
        name: python3-apt, python3-pycurl
        state: present

    - name: add Ondrej repository for later versions of PHP
      apt_repository:
        repo: 'ppa:ondrej/php'
        update_cache: yes

    - name: Install required packages and dependencies
      apt:
        state: present
        name:
          - acl
          - git
          - curl
          - unzip
          - sendmail
          - apache2
          - php8.2-common
          - php8.2-cli
          - php8.2-dev
          - php8.2-gd
          - php8.2-curl
          - php8.2-opcache
          - php8.2-xml
          - php8.2-mbstring
          - php8.2-pdo
          - php8.2-mysql
          - php8.2-apcu
          - libpcre3-dev
          - libapache2-mod-php8.2
          - python3-mysqldb
          - mysql-server


    - name: disalbe firewall
      service: name=ufw state=stopped

    - name: start Apache, mysql and php
      service: "name={{ item }} state=started enabled=yes"
      with_items: 
        - apache2
        - mysql
    
    - name: Enable apache rewrite moduel (for Drupal)
      apache2_module: name=rewrite state=present
      notify: restart apache  # This will call the handler 

    - name: add apache virtualhost for Drupal
      template:
        src: "templates/drupal.test.conf.j2"
        dest: "/etc/apache2/sites-available/{{domain}}.test.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache
    
    - name: Enable Drupal site
      command: >
        a2ensite {{domain}}.test
        creates=/etc/apache2/sites-enabled/{{domain}}.test.conf
      notify: restart apache

    - name: disable the default site
      command: >
        a2dissite 000-default
        removes=/etc/apache2/sites-enabled/000-default.conf
      notify: 
        restart apache

    - name: adjust OpCache memory setting
      lineinfile:
        dest: "/etc/php/82./apache2/conf.d/10-opcache.ini"
        regexp: "^opcache.memory_consumption"
        line: "opcache.memory_consumption = 96"
        state: present
      notify: restart apache